development:
  adapter: redis
  url: <%= ENV.include?("REDIS_HOST") ? "redis://#{ENV.fetch("REDIS_HOST")}:6379/1" : "redis://localhost:6379/1" %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.include?("REDIS_HOST") ? "redis://#{ENV.fetch("REDIS_HOST")}:6379/1" : "redis://localhost:6379/1" %>
  channel_prefix: postcard_production
